// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace OpenPol.DataLayer.WebAPI
{
    [Table("WebAPIUsers")]
    public partial class WebApiusers
    {
        [Key]
        [Column("WebAPIUsersId")]
        public long WebApiusersId { get; set; }
        [Required]
        [StringLength(200)]
        public string Email { get; set; }
        [Required]
        [StringLength(256)]
        public string Password { get; set; }
        [Required]
        [StringLength(10)]
        public string WorkerNumber { get; set; }
    }
}